matches:
  # French accents
  - trigger: "\\@e"
    replace: "é"

  - trigger: "\\@`e"
    replace: "è"

  - trigger: "\\@^e"
    replace: "ê"

  - trigger: "\\@\"e"
    replace: "ë"

  - trigger: "\\@^o"
    replace: "ô"

  - trigger: "\\@a"
    replace: "à"

  - trigger: "\\@^a"
    replace: "â"

  - trigger: "\\@^i"
    replace: "î"

  - trigger: "\\@\"i"
    replace: "ï"

  - trigger: "\\@`u"
    replace: "ù"

  - trigger: "\\@^u"
    replace: "û"

  - trigger: "\\@\"u"
    replace: "ü"

  - trigger: "\\@oe"
    replace: "œ"

  - trigger: "\\@ae"
    replace: "æ"

  - trigger: "\\@\"y"
    replace: "ÿ"

  - trigger: "\\@c"
    replace: "ç"

  - trigger: "\\@E"
    replace: "É"

  - trigger: "\\@`E"
    replace: "È"

  - trigger: "\\@^E"
    replace: "Ê"

  - trigger: "\\@\"E"
    replace: "Ë"

  - trigger: "\\@^O"
    replace: "Ô"

  - trigger: "\\@A"
    replace: "À"

  - trigger: "\\@^A"
    replace: "Â"

  - trigger: "\\@^I"
    replace: "Î"

  - trigger: "\\@\"I"
    replace: "Ï"

  - trigger: "\\@`U"
    replace: "Ù"

  - trigger: "\\@^U"
    replace: "Û"

  - trigger: "\\@\"U"
    replace: "Ü"

  - trigger: "\\@OE"
    replace: "Œ"

  - trigger: "\\@AE"
    replace: "Æ"

  - trigger: "\\@\"Y"
    replace: "Ÿ"

  - trigger: "\\@C"
    replace: "Ç"

  # Em dash
  - trigger: "\\@-"
    replace: "—"

  # Math symbols
  - trigger: "\\@mprop"
    replace: "∝"

  - trigger: "\\@mapprox"
    replace: "≈"

  - trigger: "\\@mtheta"
    replace: "Θ"

  # Superscript Numbers
  - trigger: "\\@sp0"
    replace: "⁰"

  - trigger: "\\@sp1"
    replace: "¹"

  - trigger: "\\@sp2"
    replace: "²"

  - trigger: "\\@sp3"
    replace: "³"

  - trigger: "\\@sp4"
    replace: "⁴"

  - trigger: "\\@sp5"
    replace: "⁵"

  - trigger: "\\@sp6"
    replace: "⁶"

  - trigger: "\\@sp7"
    replace: "⁷"

  - trigger: "\\@sp8"
    replace: "⁸"

  - trigger: "\\@sp9"
    replace: "⁹"

  # Subscript Numbers
  - trigger: "\\@sb0"
    replace: "₀"

  - trigger: "\\@sb1"
    replace: "₁"

  - trigger: "\\@sb2"
    replace: "₂"

  - trigger: "\\@sb3"
    replace: "₃"

  - trigger: "\\@sb4"
    replace: "₄"

  - trigger: "\\@sb5"
    replace: "₅"

  - trigger: "\\@sb6"
    replace: "₆"

  - trigger: "\\@sb7"
    replace: "₇"

  - trigger: "\\@sb8"
    replace: "₈"

  - trigger: "\\@sb9"
    replace: "₉"
